import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { LotTrackingPolicy, Prisma, StockMovementType } from '@prisma/client';
import { PrismaService } from '../../core/database/prisma.service';
import { CreateStockMovementDto } from './dto/create-stock-movement.dto';
import { CreateProductLotDto } from './dto/create-product-lot.dto';
@Injectable()
export class InventoryService {
  constructor(private readonly prisma: PrismaService) {}
  async createLot(tenantId:string,storeId:string,actorUserId:string,dto:CreateProductLotDto){const quantity=new Prisma.Decimal(dto.quantity);if(!quantity.isFinite()||quantity.lte(0))throw new BadRequestException('A quantidade do lote deve ser maior que zero.');const expiresAt=dto.expiresAt?new Date(dto.expiresAt):null;if(expiresAt&&Number.isNaN(expiresAt.getTime()))throw new BadRequestException('Validade inválida.');return this.prisma.$transaction(async tx=>{const product=await tx.product.findFirst({where:{id:dto.productId,tenantId,active:true,stores:{some:{storeId}}},select:{id:true,lotTrackingPolicy:true,stores:{where:{storeId},select:{lotTrackingPolicy:true}},section:{select:{lotTrackingPolicy:true,category:{select:{lotTrackingPolicy:true}}}}}});if(!product)throw new NotFoundException('Produto não encontrado para esta loja.');const policy=product.stores[0]?.lotTrackingPolicy??product.lotTrackingPolicy??product.section?.lotTrackingPolicy??product.section?.category.lotTrackingPolicy??LotTrackingPolicy.OPTIONAL;if(policy===LotTrackingPolicy.NONE)throw new BadRequestException('Este produto não está configurado para controlar lotes.');if(policy===LotTrackingPolicy.REQUIRED&&!expiresAt)throw new BadRequestException('A validade é obrigatória para este produto.');await tx.$queryRaw`SELECT "id" FROM "StockBalance" WHERE "storeId" = ${storeId}::uuid AND "productId" = ${dto.productId}::uuid FOR UPDATE`;const balance=await tx.stockBalance.findUnique({where:{storeId_productId:{storeId,productId:dto.productId}}});if(!balance)throw new NotFoundException('Saldo do produto não encontrado.');const before=balance.physicalQuantity,after=before.plus(quantity);const lot=await tx.productLot.upsert({where:{storeId_productId_code:{storeId,productId:dto.productId,code:dto.code.trim()}},update:{quantity:{increment:quantity},expiresAt,costPrice:dto.costPrice?new Prisma.Decimal(dto.costPrice):undefined,status:'ACTIVE'},create:{tenantId,storeId,productId:dto.productId,code:dto.code.trim(),expiresAt,quantity,costPrice:dto.costPrice?new Prisma.Decimal(dto.costPrice):undefined}});await tx.stockBalance.update({where:{id:balance.id},data:{physicalQuantity:after}});await tx.stockMovement.create({data:{tenantId,storeId,productId:dto.productId,lotId:lot.id,type:StockMovementType.PURCHASE,quantity,quantityBefore:before,quantityAfter:after,reason:'Entrada de lote',reference:lot.code,actorUserId}});return lot},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
  async listLots(tenantId:string,storeId:string,productId:string){return this.prisma.productLot.findMany({where:{tenantId,storeId,productId},orderBy:[{expiresAt:'asc'},{receivedAt:'asc'}]})}
  async move(tenantId:string,storeId:string,actorUserId:string,dto:CreateStockMovementDto){const quantity=new Prisma.Decimal(dto.quantity);if(!quantity.isFinite()||quantity.lte(0))throw new BadRequestException('A quantidade deve ser maior que zero.');const direction=['PURCHASE','ADJUSTMENT_IN','RETURN'].includes(dto.type)?1:-1;return this.prisma.$transaction(async tx=>{const product=await tx.product.findFirst({where:{id:dto.productId,tenantId,active:true,stores:{some:{storeId}}},select:{id:true}});if(!product)throw new NotFoundException('Produto não encontrado para esta loja.');await tx.$queryRaw`SELECT "id" FROM "StockBalance" WHERE "storeId" = ${storeId}::uuid AND "productId" = ${dto.productId}::uuid FOR UPDATE`;const balance=await tx.stockBalance.findUnique({where:{storeId_productId:{storeId,productId:dto.productId}}});if(!balance)throw new NotFoundException('Saldo do produto não encontrado.');const before=balance.physicalQuantity,after=direction>0?before.plus(quantity):before.minus(quantity);if(after.lt(0))throw new BadRequestException('Estoque insuficiente para esta saída.');if(after.lt(balance.reservedQuantity))throw new BadRequestException('A operação violaria o estoque já reservado.');const movement=await tx.stockMovement.create({data:{tenantId,storeId,productId:dto.productId,type:dto.type as StockMovementType,quantity:direction>0?quantity:quantity.negated(),quantityBefore:before,quantityAfter:after,reason:dto.reason?.trim(),reference:dto.reference?.trim(),actorUserId}});await tx.stockBalance.update({where:{id:balance.id},data:{physicalQuantity:after}});await tx.auditLog.create({data:{tenantId,actorId:actorUserId,action:'STOCK_MOVEMENT',entityType:'StockMovement',entityId:movement.id,after:{productId:dto.productId,type:dto.type,quantity:quantity.toString(),before:before.toString(),after:after.toString()}}});return movement},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
  async alerts(tenantId:string,storeId:string){const products=await this.prisma.product.findMany({where:{tenantId,active:true,stores:{some:{storeId}}},include:{stores:{where:{storeId}},balances:{where:{storeId}},section:{include:{category:true}}}});return products.map(product=>{const balance=product.balances[0],store=product.stores[0],availableQuantity=balance?balance.physicalQuantity.minus(balance.reservedQuantity):new Prisma.Decimal(0),minimumQty=store?.minimumQty??product.section?.minimumQty??product.section?.category.minimumQty??null,maximumQty=store?.maximumQty??product.section?.maximumQty??product.section?.category.maximumQty??null,reorderPoint=store?.reorderPoint??product.section?.reorderPoint??product.section?.category.reorderPoint??minimumQty,rupture=availableQuantity.lte(0),belowMinimum=minimumQty?availableQuantity.lt(minimumQty):false,shouldReorder=reorderPoint?availableQuantity.lte(reorderPoint):false,suggestedPurchaseQty=maximumQty&&availableQuantity.lt(maximumQty)?maximumQty.minus(availableQuantity):null;return{productId:product.id,productName:product.name,availableQuantity,minimumQty,maximumQty,reorderPoint,rupture,belowMinimum,shouldReorder,suggestedPurchaseQty}}).filter(a=>a.rupture||a.belowMinimum||a.shouldReorder)}
  async promotionSuggestions(tenantId:string,storeId:string){const now=new Date(),near=new Date(now.getTime()+30*86400000);const lots=await this.prisma.productLot.findMany({where:{tenantId,storeId,status:'ACTIVE',quantity:{gt:0},expiresAt:{not:null,lte:near}},include:{product:{include:{stores:{where:{storeId},select:{salePrice:true}}}}},orderBy:{expiresAt:'asc'}});return lots.map(lot=>{const days=Math.max(0,Math.ceil(((lot.expiresAt as Date).getTime()-now.getTime())/86400000));const stock=Number(lot.quantity),base=Number(lot.product.stores[0]?.salePrice??0);let discount=days<=3?30:days<=7?20:days<=15?12:8;if(stock>=100)discount=Math.min(45,discount+10);const promotionalPrice=base>0?Math.max(0.01,Number((base*(1-discount/100)).toFixed(2))):null;return{productId:lot.productId,productName:lot.product.name,lotId:lot.id,lotCode:lot.code,expiresAt:lot.expiresAt,daysToExpire:days,lotQuantity:lot.quantity,basePrice:lot.product.stores[0]?.salePrice??null,suggestedDiscountPercent:discount,suggestedPrice:promotionalPrice,reason:days<=7?'Validade crítica: sugerir promoção imediata':'Validade próxima: reduzir risco de perda'}})}
  async balance(tenantId:string,storeId:string,productId:string){const balance=await this.prisma.stockBalance.findFirst({where:{tenantId,storeId,productId}});if(!balance)throw new NotFoundException('Saldo não encontrado.');return{...balance,availableQuantity:balance.physicalQuantity.minus(balance.reservedQuantity)}}
}
