import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PromotionStatus } from '@prisma/client';
import { PrismaService } from '../../core/database/prisma.service';

@Injectable()
export class PromotionsService {
  constructor(private readonly prisma: PrismaService) {}

  async list(tenantId:string,storeId:string){return this.prisma.promotion.findMany({where:{tenantId,storeId},include:{product:{select:{id:true,name:true,stores:{where:{storeId},select:{salePrice:true}}}},lot:{select:{id:true,code:true,expiresAt:true}}},orderBy:{startsAt:'desc'}}).then(items=>items.map(item=>({...item,productName:item.product.name,basePrice:item.product.stores[0]?.salePrice??null,promotionPrice:item.promotionalPrice,suggestedDiscountPercent:item.product.stores[0]?.salePrice&&item.promotionalPrice?item.product.stores[0].salePrice.minus(item.promotionalPrice).div(item.product.stores[0].salePrice).mul(100):item.percentOff})))}

  async create(tenantId:string,storeId:string,actorId:string,dto:any){const startsAt=new Date(dto.startsAt),endsAt=dto.endsAt?new Date(dto.endsAt):null;if(Number.isNaN(startsAt.getTime())||(endsAt&&Number.isNaN(endsAt.getTime())))throw new BadRequestException('Datas de promoção inválidas.');if(endsAt&&endsAt<=startsAt)throw new BadRequestException('O fim da promoção deve ser posterior ao início.');if(dto.promotionalPrice==null&&dto.percentOff==null)throw new BadRequestException('Informe preço promocional ou percentual de desconto.');if(dto.promotionalPrice!=null&&Number(dto.promotionalPrice)<=0)throw new BadRequestException('O preço promocional deve ser maior que zero.');if(dto.percentOff!=null&&(Number(dto.percentOff)<=0||Number(dto.percentOff)>=100))throw new BadRequestException('O desconto deve ser maior que zero e menor que 100%.');const product=await this.prisma.product.findFirst({where:{id:dto.productId,tenantId,active:true,stores:{some:{storeId}}},select:{id:true,name:true}});if(!product)throw new NotFoundException('Produto não encontrado nesta loja.');if(dto.lotId){const lot=await this.prisma.productLot.findFirst({where:{id:dto.lotId,tenantId,storeId,productId:product.id,status:'ACTIVE'},select:{id:true}});if(!lot)throw new BadRequestException('Lote inválido para o produto e loja selecionados.');}const promotion=await this.prisma.promotion.create({data:{tenantId,storeId,productId:product.id,lotId:dto.lotId||null,title:String(dto.title||`Oferta: ${product.name}`).trim(),status:(dto.status as PromotionStatus)||'DRAFT',promotionalPrice:dto.promotionalPrice==null?null:dto.promotionalPrice,percentOff:dto.percentOff==null?null:dto.percentOff,startsAt,endsAt}});await this.prisma.auditLog.create({data:{tenantId,actorId,action:'CREATE',entityType:'Promotion',entityId:promotion.id,after:{productId:product.id,lotId:promotion.lotId,status:promotion.status,promotionalPrice:promotion.promotionalPrice?.toString()??null,percentOff:promotion.percentOff?.toString()??null,startsAt:promotion.startsAt,endsAt:promotion.endsAt}}});return promotion}

  async commercialSuggestions(tenantId:string,storeId:string){const since=new Date(Date.now()-30*86400000);const [balances,items,lots]=await Promise.all([this.prisma.stockBalance.findMany({where:{tenantId,storeId},include:{product:{include:{stores:{where:{storeId},select:{salePrice:true}}}}}}),this.prisma.orderItem.groupBy({by:['productId'],where:{order:{tenantId,storeId,status:{in:['CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','DELIVERED']},createdAt:{gte:since}}},_sum:{quantity:true}}),this.prisma.productLot.findMany({where:{tenantId,storeId,status:'ACTIVE',quantity:{gt:0}},select:{productId:true,quantity:true}})]);const sold=new Map(items.map(i=>[i.productId,Number(i._sum.quantity??0)]));const lotQty=new Map<string,number>();for(const lot of lots)lotQty.set(lot.productId,(lotQty.get(lot.productId)??0)+Number(lot.quantity));return balances.map(b=>{const physical=Number(b.physicalQuantity),reserved=Number(b.reservedQuantity),available=Math.max(0,physical-reserved),sales30=sold.get(b.productId)??0,lotQuantity=lotQty.get(b.productId)??0,turnover=sales30>0?available/sales30:Infinity;let discount=0,reason='';if(sales30===0&&available>0){discount=lotQuantity>=physical*0.8?20:15;reason='Produto sem venda confirmada nos últimos 30 dias';}else if(turnover>=3){discount=12;reason='Estoque para mais de 90 dias no ritmo atual de vendas';}else if(turnover>=2){discount=8;reason='Estoque para mais de 60 dias no ritmo atual de vendas';}if(!discount)return null;const base=Number(b.product.stores[0]?.salePrice??0),suggestedPrice=base>0?Number((base*(1-discount/100)).toFixed(2)):null;return{productId:b.productId,productName:b.product.name,availableQuantity:available,salesLast30Days:sales30,estimatedStockDays:sales30>0?Math.ceil((available/sales30)*30):null,suggestedDiscountPercent:discount,suggestedPrice,reason}}).filter(Boolean)}

  async setStatus(tenantId:string,storeId:string,actorId:string,id:string,status:PromotionStatus){const current=await this.prisma.promotion.findFirst({where:{id,tenantId,storeId}});if(!current)throw new NotFoundException('Promoção não encontrada.');const updated=await this.prisma.promotion.update({where:{id},data:{status}});await this.prisma.auditLog.create({data:{tenantId,actorId,action:'STATUS_CHANGE',entityType:'Promotion',entityId:id,before:{status:current.status},after:{status:updated.status}}});return updated}
}
