const API_BASE=import.meta.env.VITE_API_URL||'http://localhost:3000';
const ACCESS_KEY='chama.accessToken';
const REFRESH_KEY='chama.refreshToken';
const STORE_KEY='chama.storeId';
export class ApiError extends Error{constructor(public status:number,message:string,public code?:string){super(message)}}
export function setSession(accessToken:string,refreshToken:string){sessionStorage.setItem(ACCESS_KEY,accessToken);sessionStorage.setItem(REFRESH_KEY,refreshToken)}
export function clearSession(){sessionStorage.removeItem(ACCESS_KEY);sessionStorage.removeItem(REFRESH_KEY);sessionStorage.removeItem(STORE_KEY)}
export function setStoreId(storeId:string){sessionStorage.setItem(STORE_KEY,storeId)}
export function getStoreId(){return sessionStorage.getItem(STORE_KEY)}
async function refreshAccessToken(){const refreshToken=sessionStorage.getItem(REFRESH_KEY);if(!refreshToken)throw new ApiError(401,'Sessão expirada');const res=await fetch(`${API_BASE}/auth/refresh`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken})});if(!res.ok){clearSession();throw new ApiError(401,'Sessão expirada')};const data=await res.json() as {accessToken:string;refreshToken:string};setSession(data.accessToken,data.refreshToken);return data.accessToken}
export async function api<T>(path:string,init:RequestInit={},retried=false):Promise<T>{const headers=new Headers(init.headers);headers.set('Accept','application/json');if(init.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const token=sessionStorage.getItem(ACCESS_KEY);if(token)headers.set('Authorization',`Bearer ${token}`);const storeId=getStoreId();if(storeId)headers.set('x-store-id',storeId);const res=await fetch(`${API_BASE}${path}`,{...init,headers});if(res.status===401&&!retried){try{await refreshAccessToken();return api<T>(path,init,true)}catch{throw new ApiError(401,'Sessão expirada')}}const text=await res.text();let data:unknown=null;try{data=text?JSON.parse(text):null}catch{data=null}if(!res.ok){const body=data as {message?:string|string[];code?:string}|null;const message=Array.isArray(body?.message)?body!.message.join(', '):body?.message;throw new ApiError(res.status,message||'Não foi possível concluir a operação',body?.code)}return data as T}
